### ISSUE TITLE
Wrong dimension in the documentation?

### ISSUE THREAD

**Issue by dschaehi** [ofnote/tsalib#16]
This is a great library! I am wondering whether `'b,1,d'` should be `'b,l,d'` in the following assignment that I found in README.md:
`b: 'b,1,d' = alignto((a,'bd'), 'bld')`

**Comment by ekshaks** [comment]
The example is correct. `alignto`, by default, creates new dimensions of size 1. With argument `tile=True`, it matches/expands to the target dimension.  One reason behind this behavior is that native broadcast in most libraries will take care of the 'expansion' later.

Thanks for the question. I believe this needs to be clarified better in the docs.

**Comment by dschaehi** [comment]
I think I now understand the purpose of `alignto`. Thanks.
